site: pozuhtuhv
title: pozuhtuhv
greetings: "minimal: less is more"
description: "minimal: less is more"
lang: en-US
timezone: Asia/Seoul
repo: https://github.com/pozuhtuhv/pozuhtuhv.github.io # site repo [optional]
data-theme: dark # default theme "dark" | "light"

author:
  name: pozuhtuhv
  bio: "minimal: less is more"
  userpicture: /assets/img/computersolo.jpg # img path
  username: Hyeounseok-Cho # general username
  github: pozuhtuhv # github username
  twitter: pozuhtuhv # twitter username
  mastodon: # mastodon profile (ex. mastodon.social/@my_username)
  linkedin: # linkedin profile
  email: pozuhtuhv@email.com # email adress

# URL settings
url: "https://pozuhtuhv.github.io" # Domain Name of host. [username].github.io for github pages
baseurl: "" # sub folder for jekyll site. only if jekyll site not in root of host. leave blank if not wishd. always add / in front.
permalink: pretty

vscode_path: "C:/Users/pozuhtuhv/Desktop/pozuhtuhv.github.io" # path to your vscode workspace (for footer link)

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

exclude:
  - .jekyll-cache
  - .obsidian
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md
  - CONTRIBUTING.md
  
compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]

sass:
  sass_dir: _sass
  style: compressed

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-relative-links

collections:
  pages:
    output: true
    permalink: /:name
  posts:
    output: true
    permalink: /:year/:month/:day/:slug
  
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "tag"

relative_links:
  enabled:     true
  collections: false