site: pozuhtuhv
title: "포장되지 않는 간결함."
greetings: "포장되지 않는 간결함."
description: "less in more"
lang: en-US
timezone: Asia/Seoul
repo: https://github.com/pozuhtuhv/pozuhtuhv.github.io # site repo [optional]

author:
  name: pozuhtuhv
  bio: "minimal: less in more"
  userpicture: /assets/img/computersolo.jpg # img path
  username: Hyeounseok-Cho # general username
  github: pozuhtuhv # github username
  email: pozuhtuhv@email.com # email adress

spec:
  cpu: Apple M1 or Intel i5
  ram: 8GB
  storage: 256GB SSD
  os: macOS or Windows 11
  python: 3.11.5 and 3.8.7
  python_venv_path: Only /desktop/[folder]
  ide: Visual Studio Code

# URL settings
url: "https://pozuhtuhv.github.io" # Domain Name of host. [username].github.io for github pages
baseurl: "" # sub folder for jekyll site. only if jekyll site not in root of host. leave blank if not wishd. always add / in front.
permalink: pretty

vscode_path_win: "C:/Users/pozuhtuhv/Desktop/pozuhtuhv.github.io"
vscode_path_mac: "/Users/pozuhtuhv/Desktop/pozuhtuhv.github.io"

# SEO Related
google_site_verification: "iD1CAgKMzTXNTOmz_cbPmrHX7Nxd4toYeCwBC5ZAdKM"

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

exclude:
  - .jekyll-cache
  - .obsidian
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md
  - CONTRIBUTING.md
  
compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]

sass:
  sass_dir: _sass
  style: compressed

plugins:
  - jekyll-paginate
  - jekyll-relative-links
  
collections:
  pages:
    output: true
    permalink: /:name
  posts:
    output: true
    permalink: /:year/:month/:day/:slug
  
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

relative_links:
  enabled: true
  collections: false