site: pozuhtuhv
title: pozuhtuhv
greetings: Hello there! 👋
description: >-
  just a minimalist, personal blog
lang: en-US
timezone: Asia/Seoul
repo: https://github.com/pozuhtuhv # site repo [optional]
data-theme: dark # default theme "dark" | "light"
discus-identifier: # replace with your disqus shortname
comments-enabled: true # true to enable disqus comments, false to hide them

author:
  name: pozuhtuhv
  bio: just a minimalist, personal blog
  userpicture: # img path
  username: pozuhtuhv # general username
  github: pozuhtuhv # github username
  twitter: pozuhtuhv # twitter username
  mastodon: # mastodon profile (ex. mastodon.social/@my_username)
  linkedin: # linkedin profile
  email: pozuhtuhv@email.com # email adress

# Font Settings
googlewebfonts: family=Play:wght@400;700&family=Source+Code+Pro:ital,wght@0,200;0,300;0,400;0,600;0,700;0,900;1,300;1,400;1,500;1,600;1,700;1,900

# URL settings
url: "https://pozuhtuhv.github.io" # Domain Name of host. [username].github.io for github pages
baseurl: "" # sub folder for jekyll site. only if jekyll site not in root of host. leave blank if not wishd. always add / in front.
permalink: pretty

# local
# url: "http://localhost:4000" # 
# baseurl: "" # 


markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge


exclude:
  - .jekyll-cache
  - .obsidian
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md
  - CONTRIBUTING.md
  
compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]

sass:
  sass_dir: _sass
  style: compressed

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-relative-links

collections:
  pages:
    output: true
    permalink: /:name
  posts:
    output: true
    permalink: /:year/:month/:day/:slug
  
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "tag"

relative_links:
  enabled:     true
  collections: false


